services:
  - type: web
    name: aviator-backend-web
    runtime: python
    plan: free
    rootDir: django_backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_unZLlG7Fk2hz@ep-patient-rice-aq450a65-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: DATABASE_CONN_MAX_AGE
        value: "0"

  - type: worker
    name: aviator-backend-monitor
    runtime: python
    plan: starter
    rootDir: django_backend
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py run_monitor_worker
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_unZLlG7Fk2hz@ep-patient-rice-aq450a65-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: DATABASE_CONN_MAX_AGE
        value: "0"

databases:
  - name: aviator-backend-db
    plan: free
